
package movies;
// Generated Apr 21, 2011 4:44:18 PM by Hibernate Tools 3.2.1.GA

/**
 * Genre generated by hbm2java
 */
public class Genre implements java.io.Serializable
{

    private String genreType;

    public Genre()
    {
        
    }

    public Genre(String genreType)
    {
        this.genreType = genreType;
    }

    public String getGenreType()
    {
        return this.genreType;
    }

    public void setGenreType(String genreType)
    {
        this.genreType = genreType;
    }
}
