package movies;
// Generated Apr 21, 2011 4:44:18 PM by Hibernate Tools 3.2.1.GA



/**
 * Movie generated by hbm2java
 */
public class Movie  implements java.io.Serializable {


     private Integer id;
     private String movieName;
     private String genre;

    public Movie() {
    }

    public Movie(String movieName, String genre) {
       this.movieName = movieName;
       this.genre = genre;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getMovieName() {
        return this.movieName;
    }
    
    public void setMovieName(String movieName) {
        this.movieName = movieName;
    }
    public String getGenre() {
        return this.genre;
    }
    
    public void setGenre(String genre) {
        this.genre = genre;
    }




}


